### ISSUE TITLE
AttributeError: 'HTTPClient' object has no attribute '_session'

### ISSUE THREAD

**Issue by raluvy95** [fourjr/discord-cli#4]
When I run `py main.py -t='token' -c='channel-id'` and I got an error:

![image](https://user-images.githubusercontent.com/43247023/57939516-2f639a00-78d3-11e9-827e-a96c8313f69f.png)

p.s. I used Python 3.6.6 and discord.py v1.0.1a

**Comment by magistau** [comment]
the same
